/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.group_six.risc_game.client;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Client client = new Client();
        client.joinGame("test001", 2);

    }
}
